### ISSUE TITLE
Requirement for Real Time Clock and Secure Time Update

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#12]
Requests of nonce based accesstokens/keys have been made to the list. Follow up.

Request from WG: http://www.ietf.org/mail-archive/web/ace/current/msg01554.html

**Comment by LudwigSeitz** [comment]
Not sure what you mean here Erik, could you clarify?

**Comment by erwah** [comment]
http://www.ietf.org/mail-archive/web/ace/current/msg01554.html

**Comment by hannestschofenig** [comment]
In his email to the list Renzo asked a very good question, namely what are our requirements for the Resource Server (RS). If we use DTLS/TLS for communication, use certificates, and access tokens with expiry information then there is a question on how the RS should actually determine the validity of those.

In his email write-up he proposed to access nonces to access tokens and those are not very useful since this turns the access tokens into one-time tokens. If the access tokens do not contain any expiry information then the revocation mechanism has to ensure that they are replaced somehow. One way to deal with this problem it to use Token Introspection to do the verification of the access token at the authorization server itself. Of course, this adds an overhead. For the cases where this overhead is not acceptable it would be necessary for the resource server to receive revocation notifications from the authorization server. This would typically require the RS to register itself with the AS and to keep the connnection alive.

**Comment by LudwigSeitz** [comment]
I have seen a few industrial use cases where the sensors have RTC-chips (real-time clock) and can thus reliably measure time. So certain use cases can just be covered with regular expiry.

For devices without the means to reliably measure time, we could still use a sequence number approach (see e.g. https://tools.ietf.org/html/draft-selander-ace-object-security-03#section-7), which is similar to the nonce approach, but with the added advantage that you can compare recently observed sequence numbers and see if they are close to each other. Not as good as expiry or online validation, but better than nonces.

**Comment by LudwigSeitz** [comment]
I wrote some text on this in section 5.6. I'm closing this until someone protests.
