### ISSUE TITLE
Optimizations section

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#16]
Keep or start defining, if defining do it in other drafts? We have a bunch of suggestions for optimizations to be done in the optimizations section. Keep as is or start to profile?

**Comment by LudwigSeitz** [comment]
I will remove the part about RFC4680 since we determined that we cannot transfer data that is used in the DTLS handshake using that extension. That leaves the reference token and introspection. Depending on which deployment options we specify in detail, this will either end up in the main part of the doc, or be yanked out. Therefore I'm closing this. There won't be an optimizations section anymore as far as I can tell.

**Comment by LudwigSeitz** [comment]
Note that I'm also yanking the 'tktn' parameter in 5.1 because of this. I'm keeping the text in a separate file in case we need to re-use it.
