### ISSUE TITLE
Define Communication Security Protocol.

### ISSUE THREAD

**Issue by erwah** [LudwigSeitz/ace-oauth#4]
We need to make sure that TLS, DTLS and OSCOAP can be defined, maybe even create a IANA registry for them.

**Comment by samuelerdtman** [comment]
https://mailarchive.ietf.org/arch/msg/ace/BClpJNwVZT-eY5na82Cd_jjOSHg

- The client sends the POST request to /token at AS.  The request contains the public key of the client and the Audience parameter set to "tempSensorInLivingRoom".
- MS: There is no public-key in the request payload of Figure 3? Also some explanation of 'client_id' and 'client_secret' would be useful. I checked the appendix and didn't find enough information on what is the role of client_secret?

Samuel: the reason for not having a key in the request could be that the key is symmetric and, but that could be clearer. This relates to the CSP (communication security protocol) that might need to be more specific e.g. DTLS-PreSharedKey or DTLS-RawPublicKey. Some of this is somewhat covered by https://github.com/LudwigSeitz/ace-oauth/issues/4
For 'client_id' and 'client_secret' I don´t know if it should be explained here (in this document) or refereed to the OAuth2 description, opinions?

**Comment by LudwigSeitz** [comment]
I see that we already defined some parameters for this, but the were commented out, does anyone remember why?  (search for "rpk").

**Comment by LudwigSeitz** [comment]
I found the reason for removing "cs" parameter. The cipher suite is negotiated in TLS/DTLS anyway, so we do not need to provide this information.

**Comment by LudwigSeitz** [comment]
I have an approach that I would like some comments on: For object security, the Client Information needs to provide the necessary parameters in order to establish a security context between client and RS. However the specifics of these parameters and processing rules need to be defined in the object security spec, not here. So my idea was to define a generic "Object Security Context" container object here and leave it to the Object Security specs to define its contents and processing rules. 
What do you think of this?

**Comment by samuelerdtman** [comment]
I think that could be okay for object security but we also have the DTLS (and maybe TLS) case also which needs parameters e.g. if the communication will be based on a raw public key from the server that key needs to be provided to the client in the client information.
Another challenge is that when I read the object security draft last time if felt relatively fare from done i.e. this draft might be stalled by the object security draft.

**Comment by LudwigSeitz** [comment]
> I think that could be okay for object security but we also have the DTLS (and maybe TLS) case also which needs parameters e.g. if the communication will be based on a raw public key from the server that key needs to be provided to the client in the client information.

Exactly, but for DTLS and TLS the parameters are defined in rather stable RFCs, so we can define the necessary identifiers for communicating them here (which is what I plan to do before closing this).

> Another challenge is that when I read the object security draft last time if felt relatively fare from done i.e. this draft might be stalled by the object security draft.

This is why I'm trying to put a more generic container here, that can accommodate parameters defined by any object security solution in the future. The alternative would be to leave object security out entirely, but I think this is a better way. Basically we remove all references to draft-selander (sorry Göran) and replace them with generic text about a future object security solution (which I'm quite convinced we will eventually get, at least the 6tisch people seem to want one).

**Comment by LudwigSeitz** [comment]
More questions: If we assume we want to communicate DTLS parameters here, then we have the following cases:

A) We are using a PoP token
A.1) We are using a symmetric PoP key
A.2) We are using an asymmetric PoP key

For A.1 do we want to allow DTLS - RPK mode? Similarly for A.2 Do we want to allow DTLS -PSK mode?  I'm tending to prohibit this, because it means you have to provide the PoP key and the DTLS key separately and do the PoP verification in addition to the DTLS handshake (which means we also would need to specify a protocol for this).

B) We are using a bearer token, but we still need to provide the RS's RPK or PSK. Should I define new fields here or reuse the "key" field from the PoP-draft?

**Comment by samuelerdtman** [comment]
we need to do IANA registration for “csp” parameter and we need to setup a IANA registry for other options then those defined

we need to IANA register “rpk” under OAuth2 parameters I think.

the last two paragraphs says the same thing more or less.

**Comment by LudwigSeitz** [comment]
Fixed modulo IANA section.

**Comment by LudwigSeitz** [comment]
New issues arising:
1. The AS needs to signal to the client which PoP method it needs to use.
2. The AS needs to signal to the client how to transfer the token to the RS (default could be POST to /authz-info).

**Comment by LudwigSeitz** [comment]
Fixed these issues. I'm closing this and leaving the IANA registry for later.
